In [2]:
# K-means on IRIS dataset (K=3) — Easy, exam-ready version
import numpy as np
import pandas as pd

# 1) Load dataset
df = pd.read_csv("IRIS.csv")
points = df.iloc[:, 0:4].values   # Use only numeric columns

K = 3
np.random.seed(1)

# 2) Randomly choose 3 points as centroids
initial_idx = np.random.choice(points.shape[0], K, replace=False)
centroids = points[initial_idx]

print("Initial Centroids:\n", centroids)

# Euclidean distance function
def distance(a, b):
    return np.sqrt(np.sum((a - b)**2))

# 3) Run K-means for 10 iterations
for it in range(10):

    # Step 1: Assign points to nearest centroid
    clusters = [[] for _ in range(K)]

    for p in points:
        d = [distance(p, centroids[c]) for c in range(K)]
        cluster_id = np.argmin(d)
        clusters[cluster_id].append(p)

    # Step 2: Update centroids
    for c in range(K):
        centroids[c] = np.mean(clusters[c], axis=0)

    print(f"Iteration {it+1} completed")

# 4) Print final cluster means
print("\nFINAL CLUSTER CENTROIDS:")
for c in range(K):
    print(f"Cluster {c+1} centroid:", centroids[c])


Initial Centroids:
 [[5.8 4.  1.2 0.2]
 [5.1 2.5 3.  1.1]
 [6.6 3.  4.4 1.4]]
Iteration 1 completed
Iteration 2 completed
Iteration 3 completed
Iteration 4 completed
Iteration 5 completed
Iteration 6 completed
Iteration 7 completed
Iteration 8 completed
Iteration 9 completed
Iteration 10 completed

FINAL CLUSTER CENTROIDS:
Cluster 1 centroid: [5.006 3.418 1.464 0.244]
Cluster 2 centroid: [5.885      2.74       4.37666667 1.41833333]
Cluster 3 centroid: [6.8275 3.07   5.7    2.0625]
