In [1]:
# K-means on IRIS dataset (K=4) — short exam-ready code
import numpy as np
import pandas as pd

# 1) Load dataset
df = pd.read_csv("IRIS.csv")
points = df.iloc[:, 0:4].values   # numeric features only (shape: N x 4)

K = 4
np.random.seed(1)

# 2) Randomly pick K points from data as initial centroids
initial_idx = np.random.choice(points.shape[0], K, replace=False)
centroids = points[initial_idx]

print("Initial Centroids:\n", centroids)

# 3) Euclidean distance function
def distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

# 4) Run K-means for 10 iterations
for it in range(10):
    # a) create empty cluster lists
    clusters = [[] for _ in range(K)]

    # b) assignment step: assign each point to nearest centroid
    for p in points:
        dists = [distance(p, centroids[c]) for c in range(K)]
        cluster_id = np.argmin(dists)
        clusters[cluster_id].append(p)

    # c) update step: recompute centroids as mean of assigned points
    for c in range(K):
        centroids[c] = np.mean(clusters[c], axis=0)

    print(f"Iteration {it+1} done")

# 5) Print final cluster means
print("\nFINAL CLUSTER CENTROIDS:")
for c in range(K):
    print(f"Cluster {c+1} centroid:", centroids[c])



Initial Centroids:
 [[5.8 4.  1.2 0.2]
 [5.1 2.5 3.  1.1]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.3 0.4]]
Iteration 1 done
Iteration 2 done
Iteration 3 done
Iteration 4 done
Iteration 5 done
Iteration 6 done
Iteration 7 done
Iteration 8 done
Iteration 9 done
Iteration 10 done

FINAL CLUSTER CENTROIDS:
Cluster 1 centroid: [5.37058824 3.8        1.51764706 0.27647059]
Cluster 2 centroid: [5.885      2.74       4.37666667 1.41833333]
Cluster 3 centroid: [6.8275 3.07   5.7    2.0625]
Cluster 4 centroid: [4.81818182 3.22121212 1.43636364 0.22727273]
